server:
  domain: "localhost"
  http_port: 8080
  https_port: 8443
  agent_port: 7223
  environment: "development"  # development, staging, production
  
tls:
  cert_file: ""
  key_file: ""
  auto_cert: false  # Let's Encrypt - disabled for development

auth:
  api_key_length: 32
  hash_cost: 12    # bcrypt cost
  max_login_attempts: 5
  lockout_duration: "15m"

jwt:
  secret_key: "your-256-bit-secret-change-this-in-production"
  issuer: "shipit-server"
  audience: "shipit-users"
  access_token_expiry: "1h"
  refresh_token_expiry: "168h"  # 7 days
  algorithm: "HS256"

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  name: "shipit"
  user: "shipit_user"
  password: "shipit_dev_password"
  ssl_mode: "disable"  # disable for development
  max_connections: 25
  max_idle_connections: 5
  connection_max_lifetime: "5m"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  max_retries: 3
  pool_size: 10

tunnels:
  max_per_user: 10
  connection_pool_size: 10
  subdomain_length: 8
  default_ttl: "24h"

analytics:
  enabled: true
  retention_days: 90
  metrics_endpoint: "/metrics"

cors:
  allowed_origins: ["http://localhost:3000", "http://localhost:8080"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["Authorization", "Content-Type", "X-Requested-With"]
  allow_credentials: true

rate_limiting:
  enabled: true
  api_requests_per_minute: 100
  login_attempts_per_hour: 10
  tunnel_creation_per_hour: 20

logging:
  level: "debug"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, file 